Create lint.yml
syvita/daoos pull request #19
Opened 2021-04-24 15:47 UTC by pxydn

### plans

- will add GitHub Action linting for Typescript
- will add GitHub Action tests for Clarity contracts and building the UI

### want to do

- add GitHub Action linting for Clarity contracts

will close #18

2021-05-07 11:19 UTC, cryptopanter approved these changes

2021-06-04 15:33 UTC, cryptopanter commented
Is it a free service from Github?... And what lang does ot support? Javascript?...

2021-06-05 01:45 UTC, JMKJR commented
> Is it a free service from Github?... And what lang does ot support? Javascript?...

@cryptopanter Github actions is a free ci/cd tool that will execute some server-side job on the occurrence of some event (eg. PR, push). So we can use these actions to do things like check if our code is properly linted or complies with Typescript type checking.

2021-06-09 21:36 UTC, JMKJR commented
PR #37 Was merged into this one to complete the task of adding github actions. This PR is now ready for review @asteriabtc. Adding a Github action for custom linting of clarity contracts should be made into a separate issue.

2021-06-10 21:20 UTC, JMKJR requested changes

2021-06-10 21:20 UTC, JMKJR commented on .gitignore
> +.DS_Store
```suggestion
**/.DS_Store
```
If you want to include this in our `.gitignore`, let's make sure we also ignore .DS_Store files that could appear in subdirectories.

2021-06-10 21:24 UTC, JMKJR requested changes

2021-06-10 21:24 UTC, JMKJR commented on .gitignore
> +.DS_Store
Or add `.DS_Store` to the `.gitignore` in our `packages/contracts` folder. It's already in the `.gitignore` in `packages/ui`

2021-06-10 21:26 UTC, JMKJR approved these changes

2021-06-11 15:17 UTC, asteriabtc commented
@JMKJR gonna force merge it now.

2021-06-11 15:17 UTC, merged